# Generated by Django 4.0.6 on 2022-08-31 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_student_book_student_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.book')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.student')),
            ],
        ),
    ]
