# Generated by Django 4.0.6 on 2022-08-31 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_library_book_alter_library_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.book'),
        ),
    ]
