# Generated by Django 4.0.6 on 2022-09-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
