# Generated by Django 4.0.6 on 2022-09-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='book',
        ),
        migrations.RemoveField(
            model_name='library',
            name='book',
        ),
        migrations.AddField(
            model_name='library',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.book'),
        ),
    ]
