# Generated by Django 4.0.6 on 2022-09-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_student_book_remove_library_book_library_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='student',
        ),
        migrations.AddField(
            model_name='library',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        ),
    ]
