# Generated by Django 4.0.6 on 2022-10-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
